{
  "WorkItem": {
    "AffectedComponent": {
      "DisplayName": "",
      "Name": ""
    },
    "AssignedTo": "",
    "ClosedBy": "",
    "ClosedComment": "",
    "CommentCount": 5,
    "Custom": "",
    "Description": "From stack trace:\n\"System.ArgumentException was caught\n  HResult=-2147024809\n  Message=component\n  Source=System\n  StackTrace:\n       at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)\n       at System.ComponentModel.TypeDescriptor.GetClassName(Object component)\n       at NetOffice.RunningObjectTable.GetActiveProxyFromROT(String componentName, String className, Boolean throwOnError)\n       at NetOffice.ExcelApi.Application.GetActiveInstance()\n       at ITSR2.Bricks.Excel.ExcelApp.GetRunningInstance()\n  InnerException: \"\nDo you have an ideas about possible reason and how to solve it?",
    "HtmlDescription": "From stack trace:<br />\n&quot;System.ArgumentException was caught<br />\n  HResult=-2147024809<br />\n  Message=component<br />\n  Source=System<br />\n  StackTrace:<br />\n<pre><code>   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)\n   at System.ComponentModel.TypeDescriptor.GetClassName(Object component)\n   at NetOffice.RunningObjectTable.GetActiveProxyFromROT(String componentName, String className, Boolean throwOnError)\n   at NetOffice.ExcelApi.Application.GetActiveInstance()\n   at ITSR2.Bricks.Excel.ExcelApp.GetRunningInstance()</code></pre>\n\nInnerException: &quot;<br />\nDo you have an ideas about possible reason and how to solve it?<br />\n",
    "PlainDescription": "From stack trace:\n\"System.ArgumentException was caught\n  HResult=-2147024809\n  Message=component\n  Source=System\n  StackTrace:\n   at System.ComponentModel.TypeDescriptor.GetDescriptor(Object component, Boolean noCustomTypeDesc)\n   at System.ComponentModel.TypeDescriptor.GetClassName(Object component)\n   at NetOffice.RunningObjectTable.GetActiveProxyFromROT(String componentName, String className, Boolean throwOnError)\n   at NetOffice.ExcelApi.Application.GetActiveInstance()\n   at ITSR2.Bricks.Excel.ExcelApp.GetRunningInstance()\n\nInnerException: \"\nDo you have an ideas about possible reason and how to solve it?\n",
    "LastUpdatedBy": "gborrego",
    "LastUpdatedDate": "2017-04-10T18:05:51.593+02:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Unassigned",
      "Severity": 0,
      "Id": 0
    },
    "ProjectName": "netoffice",
    "ReportedBy": "oshtefchuk",
    "ReportedDate": "2013-12-20T13:34:24.357+01:00",
    "CanContactReportedByUser": false,
    "Status": {
      "Name": "Proposed",
      "Id": 1
    },
    "ReasonClosed": {
      "Name": "Unassigned"
    },
    "Summary": "Application.GetActiveInstance throws ArgumentException \"component\"",
    "Type": {
      "Name": "Unassigned",
      "Id": 5
    },
    "VoteCount": 2,
    "Id": 20548,
    "HasUserVoted": false
  },
  "FileAttachments": [
    {
      "FileId": 1600197,
      "FileName": "capture.PNG",
      "WorkItemId": 20548,
      "DownloadUrl": "https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=netoffice&WorkItemId=20548&FileAttachmentId=1600197"
    }
  ],
  "Comments": [
    {
      "Message": "I am experiencing the same issue on some code that used to work in the past.I suspect that some Office updates (?) occured and changes some things.",
      "PostedBy": "ControlBreak",
      "PostedDate": "2014-01-06T15:43:29.973+01:00",
      "WorkItemId": 20548,
      "Id": 203200
    },
    {
      "Message": "I have the same problem with a system running Windows 7 64bit- the admin just recently uninstalled a 32bit version of MS Office 2010 and installed a 64bit edition of MS Office 2010. My application manipulates Excel Sheets using NetOffice from an external application not an addon.\r\n\r\nWhile Excel is running in RAM all goes right (including all functionalities) but when it is not running actually I get the exact same exception as in this issue mentioned.\r\n\r\nMy best guess is to just ignore this specific exception but I would like to have this solved in a more valid way.",
      "PostedBy": "Riffer",
      "PostedDate": "2015-02-05T17:10:21.027+01:00",
      "WorkItemId": 20548,
      "Id": 203201
    },
    {
      "Message": "hey Riffer\r\n\r\nwhich NO version ???\r\n\r\ni have changed the implementation in NO 1.7.2 specialy for MS-Excel.NO 1.7.2 doesnt use the Running Object Table for Excel in GetActiveInstance(s)please make sure to use the latest NO version.\r\n\r\n*Sebastian",
      "PostedBy": "SebastianDotNet",
      "PostedDate": "2015-02-05T19:43:45.84+01:00",
      "WorkItemId": 20548,
      "Id": 203202
    },
    {
      "Message": "Sorry for my late response. Problem occuring in with NO 1.6. Will upgrade to newest version as adviced.\r\n\r\nThank you for your reply!",
      "PostedBy": "Riffer",
      "PostedDate": "2015-02-10T14:41:40.75+01:00",
      "WorkItemId": 20548,
      "Id": 203203
    },
    {
      "Message": "Hello! I am using version 1.7.3 and I am getting the same error, but not on the first attempt, that is to say,\nfrom the second attempt and forward. I am trying to get the body text from the current email message on the keyup event (caught by a keyboard hook). I observed that this error is not thrown when I use NetOffice out of the scope of the keyboard hook.\n\nAny ideas?",
      "PostedBy": "gborrego",
      "PostedDate": "2017-04-10T18:05:51.593+02:00",
      "WorkItemId": 20548,
      "Id": 208113
    }
  ],
  "CanDeleteWorkItem": true,
  "CanDeleteComments": true
}